services:
  database:
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=kason
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=apache_logs
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    ports:
      - 3000:3000
    build:
      context: ./web

  parser:
    depends_on:
      - database
    ports:
      - 4000:4000
    build:
      context: ./parser

  dataretrieval:
    depends_on:
      - database
    ports:
      - 4001:4001
    build:
      context: ./dataretrieval

volumes:
  pgdata:
